### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by PXshadow** [PXshadow/App#2]
Scroll Bar shown for Desktop and appears only when Scrolling able to be Infinitely scrolled as well as moved from the side or the mouseWheel.

**Comment by jgcop** [comment]
core.ScrollBar has no field scrollView
greets

**Comment by PXshadow** [comment]
@jgcop  Fixed with Latest Push, Cheers. 
https://github.com/PXshadow/App/blob/859e53d4110b5760c86a8aa0e649aecd508f72e7/src/core/Item.hx#L95
