### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by PXshadow** [PXshadow/App#6]

**Comment by jgcop** [comment]
in this example the navigationbar doesn't exist
is an error by compiling
greets

**Comment by PXshadow** [comment]
Hey @jgcop 
What do you mean by example? my last git push added initial support for a navigation bar it still needs a lot of work and is not functional yet so that's why I have it as an issue. If you have any recommendations of what you would like to see for a navigation bar in terms of functionality and style please let me know. 
As for erros I just updated github and haxelib release so it should be stable on all platforms now, sorry for the inconvenience. If you wish to contact me more directly on anything in the future, be it project your working on or example code for this Framework please don't hesitate [here](https://github.com/PXshadow/App/wiki/Contact).
Best Regards, Joey

**Comment by jgcop** [comment]
The error by compiling comes by the package index installation
After i switch to the github installation, the error doesn't come again

**Comment by PXshadow** [comment]
@jgcop Perfect okay 👍. I will make sure to update the haxelib version as soon as possible.
